import { defineArrayMember, defineField, defineType } from 'sanity';
import { ModelTemplateInput } from '../components/ModelTemplateInput';
import { AutoTitleInput } from '../components/AutoTitleInput';
import { AutoSlugInput } from '../components/AutoSlugInput';

export const aircraftType = defineType({
  name: 'aircraft',
  title: 'Aircraft',
  type: 'document',
  groups: [
    { name: 'identity', title: 'Identity', default: true },
    { name: 'listing', title: 'Listing' },
    { name: 'content', title: 'Content' },
    { name: 'media', title: 'Media' },
    { name: 'specs', title: 'Specifications' },
    { name: 'times', title: 'Times' },
  ],
  fields: [
    defineField({
      name: 'applyTemplate',
      title: 'Apply Model Template',
      type: 'string',
      group: 'identity',
      components: { input: ModelTemplateInput },
      description: 'Select a template to auto-fill manufacturer, model, type, and specifications',
    }),
    defineField({ name: 'manufacturer', title: 'Manufacturer', type: 'string', group: 'identity', validation: (Rule) => Rule.required() }),
    defineField({ name: 'model', title: 'Model', type: 'string', group: 'identity', validation: (Rule) => Rule.required() }),
    defineField({ name: 'year', title: 'Year', type: 'number', group: 'identity', validation: (Rule) => Rule.required() }),
    defineField({ name: 'registration', title: 'Registration', type: 'string', group: 'identity' }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'identity',
      components: { input: AutoTitleInput },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'URL slug',
      type: 'slug',
      group: 'identity',
      components: { input: AutoSlugInput },
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: 'serialNumber', title: 'Serial number', type: 'string', group: 'identity' }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'listing',
      options: { list: ['available', 'pending', 'sold'], layout: 'radio' },
      initialValue: 'available',
    }),
    defineField({
      name: 'type',
      title: 'Aircraft type',
      type: 'string',
      group: 'listing',
      options: {
        list: [
          { value: 'light-sport', title: 'Light Sport' },
          { value: 'experimental', title: 'Experimental' },
          { value: 'ultralight', title: 'Ultralight' },
          { value: 'amphibious', title: 'Amphibious' },
          { value: 'gyroplane', title: 'Gyroplane' },
        ],
        layout: 'dropdown',
      },
      initialValue: 'light-sport',
    }),
    defineField({ name: 'price', title: 'Price (USD)', type: 'number', group: 'listing', description: 'Leave empty for "Price on Request"' }),
    defineField({ name: 'featured', title: 'Featured on homepage', type: 'boolean', group: 'listing', initialValue: false }),
    defineField({ name: 'shortDescription', title: 'Short description', type: 'text', group: 'content', rows: 2, validation: (Rule) => Rule.required() }),
    defineField({ name: 'fullDescription', title: 'Full description', type: 'text', group: 'content', rows: 8 }),
    defineField({
      name: 'features',
      title: 'Features',
      type: 'array',
      group: 'content',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
    }),
    defineField({ name: 'history', title: 'History / notes', type: 'text', group: 'content', rows: 3 }),
    defineField({
      name: 'images',
      title: 'Images',
      type: 'array',
      group: 'media',
      of: [
        defineArrayMember({
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', type: 'string', title: 'Alt text', description: 'For accessibility' },
            { name: 'caption', type: 'string', title: 'Caption' },
          ],
        }),
      ],
    }),
    defineField({
      name: 'specs',
      title: 'Specifications',
      type: 'object',
      group: 'specs',
      options: { collapsible: true, collapsed: false },
      fields: [
        { name: 'cruiseSpeed', type: 'string', title: 'Cruise speed' },
        { name: 'maxSpeed', type: 'string', title: 'Max speed' },
        { name: 'stallSpeedFullFlaps', type: 'string', title: 'Stall speed (Full Flaps)' },
        { name: 'stallSpeedFlapsUp', type: 'string', title: 'Stall speed (Flaps Up)' },
        { name: 'range', type: 'string', title: 'Range' },
        { name: 'rateOfClimb', type: 'string', title: 'Rate of climb' },
        { name: 'serviceCeiling', type: 'string', title: 'Service ceiling' },
        { name: 'takeoffDistance', type: 'string', title: 'Takeoff distance' },
        { name: 'landingDistance', type: 'string', title: 'Landing distance' },
        { name: 'fuelCapacity', type: 'string', title: 'Fuel capacity' },
        { name: 'fuelBurn', type: 'string', title: 'Fuel burn' },
        { name: 'wingspan', type: 'string', title: 'Wingspan' },
        { name: 'length', type: 'string', title: 'Length' },
        { name: 'height', type: 'string', title: 'Height' },
        { name: 'wingArea', type: 'string', title: 'Wing area' },
        { name: 'emptyWeight', type: 'string', title: 'Empty weight' },
        { name: 'maxGrossWeight', type: 'string', title: 'Max gross weight' },
        { name: 'usefulLoad', type: 'string', title: 'Useful load' },
        { name: 'engine', type: 'string', title: 'Engine' },
        { name: 'horsepower', type: 'string', title: 'Horsepower' },
        { name: 'propeller', type: 'string', title: 'Propeller' },
        { name: 'avionics', type: 'string', title: 'Avionics' },
      ],
    }),
    defineField({ name: 'totalTime', title: 'Total time (hrs)', type: 'number', group: 'times' }),
    defineField({ name: 'engineTime', title: 'Engine time (hrs)', type: 'number', group: 'times' }),
    defineField({ name: 'propTime', title: 'Prop time (hrs)', type: 'number', group: 'times' }),
  ],
  preview: {
    select: { title: 'title', status: 'status', manufacturer: 'manufacturer' },
    prepare({ title, status, manufacturer }) {
      return { title: title ?? 'Untitled', subtitle: [manufacturer, status].filter(Boolean).join(' · ') };
    },
  },
});
